import { OrganizationType } from '../components/organization/type';

export const ORGANIZATIONS: OrganizationType[] = [
  {
    _id: '1',
    name: 'Projecto Jovens',
    backgroundImage: '/socialProjects/aldeia-nissi.jpeg',
    responsible: 'Portal do Volutário',
    totalVolunteers: 50,
    telephone: '222222222',
    email: 'porta@gmail.com',
    description: 'A short description about this organization',
    address: {
      province: 'Bengo',
      county: 'Luanda',
      street: 'Chicala 2',
    },
  },

  {
    _id: '2',
    name: 'Projecto Criança',
    backgroundImage: '/socialProjects/aprendizes-do-bem.jpg',
    responsible: 'Devsoft',
    totalVolunteers: 67,
    telephone: '222222222',
    email: 'porta@gmail.com',
    description: 'A short description about this organization',
    address: {
      province: 'Luanda',
      county: 'Luanda',
      street: 'Chicala 2',
    },
  },
  {
    _id: '3',
    name: 'Projecto Adulto',
    backgroundImage: '/socialProjects/arvore-do-saber.png',
    responsible: 'Portal do Volutário',
    totalVolunteers: 10,
    telephone: '222222222',
    email: 'porta@gmail.com',
    description: 'A short description about this organization',
    address: {
      province: 'Luanda',
      county: 'Luanda',
      street: 'Chicala 2',
    },
  },
  {
    _id: '4',
    name: 'Projecto Idoso',
    backgroundImage: '/socialProjects/cuerama.jpg',
    responsible: 'Portal do Volutário',
    totalVolunteers: 10,
    telephone: '222222222',
    email: 'porta@gmail.com',
    description: 'A short description about this organization',
    address: {
      province: 'Luanda',
      county: 'Luanda',
      street: 'Chicala 2',
    },
  },
  {
    _id: '5',
    name: 'Acolhe Jovem',
    backgroundImage: '/socialProjects/mosaiko.jpg',
    responsible: 'Portal do Volutário',
    totalVolunteers: 20,
    telephone: '222222222',
    email: 'porta@gmail.com',
    description: 'A short description about this organization',
    address: {
      province: 'Luanda',
      county: 'Luanda',
      street: 'Chicala 2',
    },
  },
  {
    _id: '6',
    name: 'Acolhe Idoso',
    backgroundImage: '/socialProjects/sorria-angola.jpg',
    responsible: 'Portal do Volutário',
    totalVolunteers: 70,
    telephone: '222222222',
    email: 'porta@gmail.com',
    description: 'A short description about this organization',
    address: {
      province: 'Luanda',
      county: 'Luanda',
      street: 'Chicala 2',
    },
  },
];
