import { OrganizationType } from '../components/organization/type';

export const ORGANIZATIONS: OrganizationType[] = [
  {
    _id: '1',
    name: 'Projecto Jovens',
    coverImage: '/socialProjects/aldeia-nissi.jpeg',
    responsible: 'Portal do Volutário',
    totalVolunteers: 50,
    telephone: '222222222',
    email: 'porta@gmail.com',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit, sociis turpis montes luctus ultrices sem magnis dignissim, mi dui senectus commodo dapibus ullamcorper. Gravida ultricies curae quisque mi taciti per blandit risus non dis dui, phasellus nunc imperdiet elementum nibh nullam euismod nec etiam quis aptent cubilia, himenaeos sociis faucibus class tristique dignissim diam lobortis vestibulum placerat. Id congue libero volutpat justo blandit rhoncus hac purus nulla nam, fringilla magnis dapibus ridiculus integer sapien pellentesque accumsan aliquam torquent, per aenean vitae parturient primis mi placerat conubia montes.',
    province: 'Bengo',
    county: 'Luanda',
    street: 'Chicala 2',
  },

  {
    _id: '2',
    name: 'Projecto Criança',
    coverImage: '/socialProjects/aprendizes-do-bem.jpg',
    responsible: 'Devsoft',
    totalVolunteers: 67,
    telephone: '222222222',
    email: 'porta@gmail.com',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit, sociis turpis montes luctus ultrices sem magnis dignissim, mi dui senectus commodo dapibus ullamcorper. Gravida ultricies curae quisque mi taciti per blandit risus non dis dui, phasellus nunc imperdiet elementum nibh nullam euismod nec etiam quis aptent cubilia, himenaeos sociis faucibus class tristique dignissim diam lobortis vestibulum placerat. Id congue libero volutpat justo blandit rhoncus hac purus nulla nam, fringilla magnis dapibus ridiculus integer sapien pellentesque accumsan aliquam torquent, per aenean vitae parturient primis mi placerat conubia montes.',
    province: 'Luanda',
    county: 'Luanda',
    street: 'Chicala 2',
  },
  {
    _id: '3',
    name: 'Projecto Adulto',
    coverImage: '/socialProjects/arvore-do-saber.png',
    responsible: 'Portal do Volutário',
    totalVolunteers: 10,
    telephone: '222222222',
    email: 'porta@gmail.com',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit, sociis turpis montes luctus ultrices sem magnis dignissim, mi dui senectus commodo dapibus ullamcorper. Gravida ultricies curae quisque mi taciti per blandit risus non dis dui, phasellus nunc imperdiet elementum nibh nullam euismod nec etiam quis aptent cubilia, himenaeos sociis faucibus class tristique dignissim diam lobortis vestibulum placerat. Id congue libero volutpat justo blandit rhoncus hac purus nulla nam, fringilla magnis dapibus ridiculus integer sapien pellentesque accumsan aliquam torquent, per aenean vitae parturient primis mi placerat conubia montes.',
    province: 'Luanda',
    county: 'Luanda',
    street: 'Chicala 2',
  },
  {
    _id: '4',
    name: 'Projecto Idoso',
    coverImage: '/socialProjects/cuerama.jpg',
    responsible: 'Portal do Volutário',
    totalVolunteers: 10,
    telephone: '222222222',
    email: 'porta@gmail.com',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit, sociis turpis montes luctus ultrices sem magnis dignissim, mi dui senectus commodo dapibus ullamcorper. Gravida ultricies curae quisque mi taciti per blandit risus non dis dui, phasellus nunc imperdiet elementum nibh nullam euismod nec etiam quis aptent cubilia, himenaeos sociis faucibus class tristique dignissim diam lobortis vestibulum placerat. Id congue libero volutpat justo blandit rhoncus hac purus nulla nam, fringilla magnis dapibus ridiculus integer sapien pellentesque accumsan aliquam torquent, per aenean vitae parturient primis mi placerat conubia montes.',
    province: 'Luanda',
    county: 'Luanda',
    street: 'Chicala 2',
  },
  {
    _id: '5',
    name: 'Acolhe Jovem',
    coverImage: '/socialProjects/mosaiko.jpg',
    responsible: 'Portal do Volutário',
    totalVolunteers: 20,
    telephone: '222222222',
    email: 'porta@gmail.com',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit, sociis turpis montes luctus ultrices sem magnis dignissim, mi dui senectus commodo dapibus ullamcorper. Gravida ultricies curae quisque mi taciti per blandit risus non dis dui, phasellus nunc imperdiet elementum nibh nullam euismod nec etiam quis aptent cubilia, himenaeos sociis faucibus class tristique dignissim diam lobortis vestibulum placerat. Id congue libero volutpat justo blandit rhoncus hac purus nulla nam, fringilla magnis dapibus ridiculus integer sapien pellentesque accumsan aliquam torquent, per aenean vitae parturient primis mi placerat conubia montes.',
    province: 'Luanda',
    county: 'Luanda',
    street: 'Chicala 2',
  },
  {
    _id: '6',
    name: 'Acolhe Idoso',
    coverImage: '/socialProjects/sorria-angola.jpg',
    responsible: 'Portal do Volutário',
    totalVolunteers: 70,
    telephone: '222222222',
    email: 'porta@gmail.com',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit, sociis turpis montes luctus ultrices sem magnis dignissim, mi dui senectus commodo dapibus ullamcorper. Gravida ultricies curae quisque mi taciti per blandit risus non dis dui, phasellus nunc imperdiet elementum nibh nullam euismod nec etiam quis aptent cubilia, himenaeos sociis faucibus class tristique dignissim diam lobortis vestibulum placerat. Id congue libero volutpat justo blandit rhoncus hac purus nulla nam, fringilla magnis dapibus ridiculus integer sapien pellentesque accumsan aliquam torquent, per aenean vitae parturient primis mi placerat conubia montes.',
    province: 'Luanda',
    county: 'Luanda',
    street: 'Chicala 2',
  },
];
