export default [
  {
    'id': 1,
    'name': 'Benguela',
    'slug': 'benguela',
    'organizations': [],
    'socialProjects': ['', '', '', ''],
  },
  {
    'id': 2,
    'name': 'Cabinda',
    'slug': 'cabinda',
    'organizations': [],
    'socialProjects': [],
  },
  {
    'id': 3,
    'name': 'Huambo',
    'slug': 'huambo',
    'organizations': [],
    'socialProjects': [],
  },
  {
    'id': 4,
    'name': 'Huíla',
    'slug': 'huila',
    'organizations': [],
    'socialProjects': [],
  },
  {
    'id': 5,
    'name': 'Kwanza Norte',
    'slug': 'kwanza-norte',
    'organizations': [],
    'socialProjects': [],
  },
  {
    'id': 6,
    'name': 'Kwanza sul',
    'slug': 'kwanza-sul',
    'organizations': [],
    'socialProjects': [],
  },
  {
    'id': 7,
    'name': 'Luanda',
    'slug': 'luanda',
    'organizations': [],
    'socialProjects': [],
  },
  {
    'id': 8,
    'name': 'Lunda Sul',
    'slug': 'lunda sul',
    'organizations': [],
    'socialProjects': [],
  },
  {
    'id': 9,
    'name': 'Moxico',
    'slug': 'moxico',
    'organizations': [],
    'socialProjects': [],
  },
  {
    'id': 10,
    'name': 'Uíge',
    'slug': 'uige',
    'organizations': [],
    'socialProjects': [],
  },
  {
    'id': 11,
    'name': 'Zaire',
    'slug': 'zaire',
    'organizations': [],
    'socialProjects': [],
  },
];