import prisma from '@/libs/prismadb';
import { faker } from '@faker-js/faker';

import {
  SocialOrganization,
  SocialProject,
  User,
  Event,
  EventStatus,
  Genre,
  Role,
  AccountType,
} from '@prisma/client';

// export const FAKE_USERS: (User & {
//   socialProjects: SocialProject[];
//   socialOrganizations: SocialOrganization[];
//   events: Event[];
// })[] = () => [
//   {
//     id: '1',
//     name: faker.name.fullName(),
//     email: faker.internet.email(),
//     telephone: faker.phone.number(),
//     address: faker.address.city(),
//     birthDate: new Date(),
//     county: 'Luanda',
//     genre: Genre.MASCULINO,
//     province: 'Luanda',
//     profission: faker.random.word(),
//     avatar: faker.image.avatar(),
//     role: 'VOLUNTEER',
//     hashedPassword: faker.random.alphaNumeric(),
//     createdAt: faker.date.past(),
//     updatedAt: faker.date.past(),
//     socialOrganizationIDs: [],
//     socialProjectIDs: [],
//     eventIDs: [],
//     socialOrganizations: [
//       {
//         id: '6',
//         avatar: faker.image.avatar(),
//         name: faker.name.fullName(),
//         coverImage: faker.image.animals(),
//         hashedPassword: faker.random.alphaNumeric(),
//         responsibleName: faker.name.fullName(),
//         responsibleEmail: faker.internet.email(),
//         responsiblePhone: '9535435634',
//         telephone: faker.phone.number(),
//         email: faker.internet.email(),
//         description:
//           'Lorem ipsum dolor sit amet consectetur adipiscing elit cum gravida leo, duis phasellus in aliquam conubia tincidunt vitae sem accumsan ante, rhoncus lectus habitasse fusce condimentum mi ornare fermentum litora. Ridiculus cubilia nisi ultrices a convallis facilisis leo erat sociis, mi condimentum sapien arcu semper morbi nullam commodo molestie, netus vivamus risus sociosqu maecenas pulvinar nibh elementum. Laoreet pretium aliquam molestie imperdiet nullam fermentum, aenean nisi duis phasellus blandit, sagittis inceptos venenatis dis ultrices. Pellentesque nulla per parturient suspendisse posuere sagittis, mauris tortor porta feugiat vehicula, habitant laoreet torquent dictum semper. Urna sed tellus montes lectus ullamcorper eu etiam semper, commodo risus mi ad quam curabitur ornare, sagittis odio at rutrum turpis magnis feugiat. Sollicitudin nascetur praesent mus arcu massa eget nec fringilla etiam, porta magnis parturient vulputate nunc at mattis urna, fusce torquent fermentum dui ultrices odio aliquam facilisis. Ornare laoreet quis urna dui quam nulla molestie habitant, aenean eros malesuada vel curabitur purus rutrum ante fusce, convallis aliquet morbi suspendisse a praesent posuere. Quisque viverra consequat etiam mauris scelerisque nostra, sollicitudin phasellus curabitur magna auctor mattis semper, feugiat integer eget torquent eros. Aptent per ultrices vulputate tellus eros tempor tortor class vel, facilisis viverra quisque enim rhoncus ligula iaculis consequat aliquam, hac tincidunt libero nunc aliquet porttitor vivamus sodales. Nulla ante nullam tincidunt elementum viverra turpis, dignissim sapien egestas phasellus curabitur vulputate, primis ad praesent ut neque. Ultricies feugiat sem dis tristique class ligula vitae donec nulla curae nascetur, hendrerit dictum egestas vestibulum interdum neque nibh venenatis euismod. Fusce fringilla praesent tellus egestas neque ornare dis commodo mus fermentum massa, arcu at porta cras eu aliquet pharetra nec parturient. Magna ultricies hendrerit consequat senectus ut pellentesque vel tortor dapibus, sociis egestas mauris dui nam feugiat fusce facilisi, auctor convallis velit eget posuere eu orci tempus.',
//         province: 'Luanda',
//         county: 'Luanda',
//         address: faker.address.city(),
//         createdAt: faker.date.past(),
//         updatedAt: faker.date.past(),
//         volunteerIDs: [],
//         sponsorIDs: [],
//         // sponsors: MOCKED_SPONSORS,
//         // volunteers: MOCKED_VOLUNTEERS,
//         // events: MOCKED_EVENTS,
//         // socialProjects: MOCKED_SOCIAL_PROJECTS,
//       },
//     ],
//     socialProjects: [
//       {
//         id: '11',
//         name: faker.name.fullName(),
//         coverImage: faker.image.animals(),
//         county: 'Luanda',
//         address: faker.address.city(),
//         sponsorIDs: [],
//         createdAt: faker.date.past(),
//         updatedAt: faker.date.past(),
//         socialOrganizationId: '',
//         // socialOrganization: MOCKED_SINGLE_ORG,
//         // sponsors: MOCKED_SPONSORS,
//         volunteerIDs: ['string', 'string', 'string'],
//         province: 'Luanda',
//         description: `Lorem ipsum dolor sit amet consectetur adipiscing elit, ridiculus duis fringilla at cum ultricies, massa habitasse tellus ante inceptos morbi. Dignissim in tristique nisl integer, fusce laoreet accumsan, venenatis eget suspendisse. Suscipit est commodo venenatis iaculis tempus nibh dictum, auctor blandit praesent odio vel pharetra convallis placerat, ullamcorper nostra ligula morbi egestas erat. Velit magnis cras vehicula rhoncus quam nulla, nisl per turpis suspendisse luctus, eleifend egestas scelerisque nibh nullam. Magnis vulputate nulla fusce egestas volutpat dapibus vestibulum penatibus laoreet sollicitudin augue, nam non habitasse nisi habitant ligula per vitae pulvinar cursus. Purus lacinia interdum aenean tincidunt placerat fringilla pellentesque ligula habitant tempus, tristique volutpat turpis mattis faucibus in vulputate pretium nullam erat, dis condimentum tortor molestie ac lectus natoque rhoncus netus.
//           Fringilla inceptos ante penatibus purus leo cubilia venenatis, quam laoreet nascetur congue lacinia et tempor placerat, feugiat fermentum donec hac diam a. Ullamcorper mus proin maecenas mollis lectus pharetra arcu, enim ad urna egestas non hac habitasse tempus, aenean tincidunt molestie auctor natoque nunc. Iaculis nascetur porttitor dictum eros nisi bibendum purus, class a nostra augue nibh. Cubilia eleifend lacinia montes tempor duis faucibus auctor cursus vestibulum, felis lobortis rutrum sollicitudin varius netus dis risus eget, blandit laoreet nascetur urna sem ligula volutpat magnis. Quisque etiam proin mauris sollicitudin id nibh litora euismod integer sed sociis, nostra facilisis bibendum parturient molestie pellentesque eget malesuada primis. Nullam egestas libero tempus ridiculus cubilia porttitor natoque sodales dignissim porta, quisque congue vel quam auctor tortor integer fames cum et, nec curabitur suspendisse elementum sociosqu dui mattis scelerisque hac. Sapien faucibus aenean habitant dictum dictumst pretium vitae sollicitudin curabitur cursus vivamus, tempus rhoncus viverra ornare sed consequat sociis per feugiat. Aptent bibendum fames eleifend a laoreet scelerisque volutpat pretium enim quam, condimentum nascetur justo tempor molestie auctor luctus fusce malesuada, ullamcorper dui diam mi nulla risus erat vestibulum nibh.`,
//       },
//     ],
//     events: [
//       {
//         id: '1',
//         title: 'Lorem ipsum dolor sit amet',
//         province: 'Luanda',
//         county: 'Luanda',
//         address: faker.address.city(),
//         startDate: new Date(),
//         endDate: new Date(),
//         status: EventStatus.UPCOMMING,
//         createdAt: faker.date.past(),
//         updatedAt: faker.date.past(),
//         volunteerIDs: [],
//         socialOrganizationID: '',
//         sponsorIDs: [],
//         // volunteers: MOCKED_VOLUNTEERS,
//         // sponsors: MOCKED_SPONSORS,
//         // socialOrganization: MOCKED_SINGLE_ORG,
//         // participants: MOCKED_VOLUNTEERS,
//       },
//     ],
//   },
//   {
//     id: '2',
//     name: faker.name.fullName(),
//     email: faker.internet.email(),
//     telephone: faker.phone.number(),
//     address: faker.address.city(),
//     profission: faker.random.word(),
//     avatar: faker.image.avatar(),
//     role: 'VOLUNTEER',
//     hashedPassword: faker.random.alphaNumeric(),
//     createdAt: faker.date.past(),
//     updatedAt: faker.date.past(),
//     socialOrganizationIDs: [],
//     socialProjectIDs: [],
//     eventIDs: [],
//     socialProjects: [
//       {
//         id: '11',
//         name: faker.name.fullName(),
//         coverImage: faker.image.animals(),
//         hashedPassword: faker.random.alphaNumeric(),
//         county: 'Luanda',
//         address: faker.address.city(),
//         sponsorIDs: [],
//         createdAt: faker.date.past(),
//         updatedAt: faker.date.past(),
//         socialOrganizationId: '',
//         // socialOrganization: MOCKED_SINGLE_ORG,
//         // sponsors: MOCKED_SPONSORS,
//         volunteerIDs: ['string', 'string', 'string'],
//         province: 'Luanda',
//         description: `Lorem ipsum dolor sit amet consectetur adipiscing elit, ridiculus duis fringilla at cum ultricies, massa habitasse tellus ante inceptos morbi. Dignissim in tristique nisl integer, fusce laoreet accumsan, venenatis eget suspendisse. Suscipit est commodo venenatis iaculis tempus nibh dictum, auctor blandit praesent odio vel pharetra convallis placerat, ullamcorper nostra ligula morbi egestas erat. Velit magnis cras vehicula rhoncus quam nulla, nisl per turpis suspendisse luctus, eleifend egestas scelerisque nibh nullam. Magnis vulputate nulla fusce egestas volutpat dapibus vestibulum penatibus laoreet sollicitudin augue, nam non habitasse nisi habitant ligula per vitae pulvinar cursus. Purus lacinia interdum aenean tincidunt placerat fringilla pellentesque ligula habitant tempus, tristique volutpat turpis mattis faucibus in vulputate pretium nullam erat, dis condimentum tortor molestie ac lectus natoque rhoncus netus.
//           Fringilla inceptos ante penatibus purus leo cubilia venenatis, quam laoreet nascetur congue lacinia et tempor placerat, feugiat fermentum donec hac diam a. Ullamcorper mus proin maecenas mollis lectus pharetra arcu, enim ad urna egestas non hac habitasse tempus, aenean tincidunt molestie auctor natoque nunc. Iaculis nascetur porttitor dictum eros nisi bibendum purus, class a nostra augue nibh. Cubilia eleifend lacinia montes tempor duis faucibus auctor cursus vestibulum, felis lobortis rutrum sollicitudin varius netus dis risus eget, blandit laoreet nascetur urna sem ligula volutpat magnis. Quisque etiam proin mauris sollicitudin id nibh litora euismod integer sed sociis, nostra facilisis bibendum parturient molestie pellentesque eget malesuada primis. Nullam egestas libero tempus ridiculus cubilia porttitor natoque sodales dignissim porta, quisque congue vel quam auctor tortor integer fames cum et, nec curabitur suspendisse elementum sociosqu dui mattis scelerisque hac. Sapien faucibus aenean habitant dictum dictumst pretium vitae sollicitudin curabitur cursus vivamus, tempus rhoncus viverra ornare sed consequat sociis per feugiat. Aptent bibendum fames eleifend a laoreet scelerisque volutpat pretium enim quam, condimentum nascetur justo tempor molestie auctor luctus fusce malesuada, ullamcorper dui diam mi nulla risus erat vestibulum nibh.`,
//       },
//     ],
//     socialOrganizations: [
//       {
//         id: '6',
//         avatar: faker.image.avatar(),
//         name: faker.name.fullName(),
//         coverImage: faker.image.animals(),
//         hashedPassword: faker.random.alphaNumeric(),
//         responsibleName: faker.name.fullName(),
//         responsibleEmail: faker.internet.email(),
//         responsiblePhone: '9535435634',
//         telephone: faker.phone.number(),
//         email: faker.internet.email(),
//         description:
//           'Lorem ipsum dolor sit amet consectetur adipiscing elit cum gravida leo, duis phasellus in aliquam conubia tincidunt vitae sem accumsan ante, rhoncus lectus habitasse fusce condimentum mi ornare fermentum litora. Ridiculus cubilia nisi ultrices a convallis facilisis leo erat sociis, mi condimentum sapien arcu semper morbi nullam commodo molestie, netus vivamus risus sociosqu maecenas pulvinar nibh elementum. Laoreet pretium aliquam molestie imperdiet nullam fermentum, aenean nisi duis phasellus blandit, sagittis inceptos venenatis dis ultrices. Pellentesque nulla per parturient suspendisse posuere sagittis, mauris tortor porta feugiat vehicula, habitant laoreet torquent dictum semper. Urna sed tellus montes lectus ullamcorper eu etiam semper, commodo risus mi ad quam curabitur ornare, sagittis odio at rutrum turpis magnis feugiat. Sollicitudin nascetur praesent mus arcu massa eget nec fringilla etiam, porta magnis parturient vulputate nunc at mattis urna, fusce torquent fermentum dui ultrices odio aliquam facilisis. Ornare laoreet quis urna dui quam nulla molestie habitant, aenean eros malesuada vel curabitur purus rutrum ante fusce, convallis aliquet morbi suspendisse a praesent posuere. Quisque viverra consequat etiam mauris scelerisque nostra, sollicitudin phasellus curabitur magna auctor mattis semper, feugiat integer eget torquent eros. Aptent per ultrices vulputate tellus eros tempor tortor class vel, facilisis viverra quisque enim rhoncus ligula iaculis consequat aliquam, hac tincidunt libero nunc aliquet porttitor vivamus sodales. Nulla ante nullam tincidunt elementum viverra turpis, dignissim sapien egestas phasellus curabitur vulputate, primis ad praesent ut neque. Ultricies feugiat sem dis tristique class ligula vitae donec nulla curae nascetur, hendrerit dictum egestas vestibulum interdum neque nibh venenatis euismod. Fusce fringilla praesent tellus egestas neque ornare dis commodo mus fermentum massa, arcu at porta cras eu aliquet pharetra nec parturient. Magna ultricies hendrerit consequat senectus ut pellentesque vel tortor dapibus, sociis egestas mauris dui nam feugiat fusce facilisi, auctor convallis velit eget posuere eu orci tempus.',
//         province: 'Luanda',
//         county: 'Luanda',
//         address: faker.address.city(),
//         createdAt: faker.date.past(),
//         updatedAt: faker.date.past(),
//         volunteerIDs: [],
//         sponsorIDs: [],
//         // sponsors: MOCKED_SPONSORS,
//         // volunteers: MOCKED_VOLUNTEERS,
//         // events: MOCKED_EVENTS,
//         // socialProjects: MOCKED_SOCIAL_PROJECTS,
//       },
//     ],
//     events: [
//       {
//         id: '1',
//         title: 'Lorem ipsum dolor sit amet',
//         province: 'Luanda',
//         county: 'Luanda',
//         address: faker.address.city(),
//         startDate: new Date(),
//         endDate: new Date(),
//         status: EventStatus.UPCOMMING,
//         createdAt: faker.date.past(),
//         updatedAt: faker.date.past(),
//         volunteerIDs: [],
//         socialOrganizationID: '',
//         sponsorIDs: [],
//         // volunteers: MOCKED_VOLUNTEERS,
//         // sponsors: MOCKED_SPONSORS,
//         // socialOrganization: MOCKED_SINGLE_ORG,
//         // participants: MOCKED_VOLUNTEERS,
//       },
//     ],
//   },
//   {
//     id: '3',
//     name: faker.name.fullName(),
//     email: faker.internet.email(),
//     telephone: faker.phone.number(),
//     address: faker.address.city(),
//     profission: faker.random.word(),
//     avatar: faker.image.avatar(),
//     role: 'VOLUNTEER',
//     hashedPassword: faker.random.alphaNumeric(),
//     createdAt: faker.date.past(),
//     updatedAt: faker.date.past(),
//     socialOrganizationIDs: [],
//     socialProjectIDs: [],
//     eventIDs: [],
//     socialProjects: [
//       {
//         id: '11',
//         name: faker.name.fullName(),
//         coverImage: faker.image.animals(),
//         hashedPassword: faker.random.alphaNumeric(),
//         county: 'Luanda',
//         address: faker.address.city(),
//         sponsorIDs: [],
//         createdAt: faker.date.past(),
//         updatedAt: faker.date.past(),
//         socialOrganizationId: '',
//         // socialOrganization: MOCKED_SINGLE_ORG,
//         // sponsors: MOCKED_SPONSORS,
//         volunteerIDs: ['string', 'string', 'string'],
//         province: 'Luanda',
//         description: `Lorem ipsum dolor sit amet consectetur adipiscing elit, ridiculus duis fringilla at cum ultricies, massa habitasse tellus ante inceptos morbi. Dignissim in tristique nisl integer, fusce laoreet accumsan, venenatis eget suspendisse. Suscipit est commodo venenatis iaculis tempus nibh dictum, auctor blandit praesent odio vel pharetra convallis placerat, ullamcorper nostra ligula morbi egestas erat. Velit magnis cras vehicula rhoncus quam nulla, nisl per turpis suspendisse luctus, eleifend egestas scelerisque nibh nullam. Magnis vulputate nulla fusce egestas volutpat dapibus vestibulum penatibus laoreet sollicitudin augue, nam non habitasse nisi habitant ligula per vitae pulvinar cursus. Purus lacinia interdum aenean tincidunt placerat fringilla pellentesque ligula habitant tempus, tristique volutpat turpis mattis faucibus in vulputate pretium nullam erat, dis condimentum tortor molestie ac lectus natoque rhoncus netus.
//           Fringilla inceptos ante penatibus purus leo cubilia venenatis, quam laoreet nascetur congue lacinia et tempor placerat, feugiat fermentum donec hac diam a. Ullamcorper mus proin maecenas mollis lectus pharetra arcu, enim ad urna egestas non hac habitasse tempus, aenean tincidunt molestie auctor natoque nunc. Iaculis nascetur porttitor dictum eros nisi bibendum purus, class a nostra augue nibh. Cubilia eleifend lacinia montes tempor duis faucibus auctor cursus vestibulum, felis lobortis rutrum sollicitudin varius netus dis risus eget, blandit laoreet nascetur urna sem ligula volutpat magnis. Quisque etiam proin mauris sollicitudin id nibh litora euismod integer sed sociis, nostra facilisis bibendum parturient molestie pellentesque eget malesuada primis. Nullam egestas libero tempus ridiculus cubilia porttitor natoque sodales dignissim porta, quisque congue vel quam auctor tortor integer fames cum et, nec curabitur suspendisse elementum sociosqu dui mattis scelerisque hac. Sapien faucibus aenean habitant dictum dictumst pretium vitae sollicitudin curabitur cursus vivamus, tempus rhoncus viverra ornare sed consequat sociis per feugiat. Aptent bibendum fames eleifend a laoreet scelerisque volutpat pretium enim quam, condimentum nascetur justo tempor molestie auctor luctus fusce malesuada, ullamcorper dui diam mi nulla risus erat vestibulum nibh.`,
//       },
//     ],
//     socialOrganizations: [
//       {
//         id: '6',
//         avatar: faker.image.avatar(),
//         name: faker.name.fullName(),
//         coverImage: faker.image.animals(),
//         hashedPassword: faker.random.alphaNumeric(),
//         responsibleName: faker.name.fullName(),
//         responsibleEmail: faker.internet.email(),
//         responsiblePhone: '9535435634',
//         telephone: faker.phone.number(),
//         email: faker.internet.email(),
//         description:
//           'Lorem ipsum dolor sit amet consectetur adipiscing elit cum gravida leo, duis phasellus in aliquam conubia tincidunt vitae sem accumsan ante, rhoncus lectus habitasse fusce condimentum mi ornare fermentum litora. Ridiculus cubilia nisi ultrices a convallis facilisis leo erat sociis, mi condimentum sapien arcu semper morbi nullam commodo molestie, netus vivamus risus sociosqu maecenas pulvinar nibh elementum. Laoreet pretium aliquam molestie imperdiet nullam fermentum, aenean nisi duis phasellus blandit, sagittis inceptos venenatis dis ultrices. Pellentesque nulla per parturient suspendisse posuere sagittis, mauris tortor porta feugiat vehicula, habitant laoreet torquent dictum semper. Urna sed tellus montes lectus ullamcorper eu etiam semper, commodo risus mi ad quam curabitur ornare, sagittis odio at rutrum turpis magnis feugiat. Sollicitudin nascetur praesent mus arcu massa eget nec fringilla etiam, porta magnis parturient vulputate nunc at mattis urna, fusce torquent fermentum dui ultrices odio aliquam facilisis. Ornare laoreet quis urna dui quam nulla molestie habitant, aenean eros malesuada vel curabitur purus rutrum ante fusce, convallis aliquet morbi suspendisse a praesent posuere. Quisque viverra consequat etiam mauris scelerisque nostra, sollicitudin phasellus curabitur magna auctor mattis semper, feugiat integer eget torquent eros. Aptent per ultrices vulputate tellus eros tempor tortor class vel, facilisis viverra quisque enim rhoncus ligula iaculis consequat aliquam, hac tincidunt libero nunc aliquet porttitor vivamus sodales. Nulla ante nullam tincidunt elementum viverra turpis, dignissim sapien egestas phasellus curabitur vulputate, primis ad praesent ut neque. Ultricies feugiat sem dis tristique class ligula vitae donec nulla curae nascetur, hendrerit dictum egestas vestibulum interdum neque nibh venenatis euismod. Fusce fringilla praesent tellus egestas neque ornare dis commodo mus fermentum massa, arcu at porta cras eu aliquet pharetra nec parturient. Magna ultricies hendrerit consequat senectus ut pellentesque vel tortor dapibus, sociis egestas mauris dui nam feugiat fusce facilisi, auctor convallis velit eget posuere eu orci tempus.',
//         province: 'Luanda',
//         county: 'Luanda',
//         address: faker.address.city(),
//         createdAt: faker.date.past(),
//         updatedAt: faker.date.past(),
//         volunteerIDs: [],
//         sponsorIDs: [],
//         // sponsors: MOCKED_SPONSORS,
//         // volunteers: MOCKED_VOLUNTEERS,
//         // events: MOCKED_EVENTS,
//         // socialProjects: MOCKED_SOCIAL_PROJECTS,
//       },
//     ],
//     events: [
//       {
//         id: '1',
//         title: 'Lorem ipsum dolor sit amet',
//         province: 'Luanda',
//         county: 'Luanda',
//         address: faker.address.city(),
//         startDate: new Date(),
//         endDate: new Date(),
//         status: EventStatus.UPCOMMING,
//         createdAt: faker.date.past(),
//         updatedAt: faker.date.past(),
//         volunteerIDs: [],
//         socialOrganizationID: '',
//         sponsorIDs: [],
//         // volunteers: MOCKED_VOLUNTEERS,
//         // sponsors: MOCKED_SPONSORS,
//         // socialOrganization: MOCKED_SINGLE_ORG,
//         // participants: MOCKED_VOLUNTEERS,
//       },
//     ],
//   },
//   {
//     id: '4',
//     name: faker.name.fullName(),
//     email: faker.internet.email(),
//     telephone: faker.phone.number(),
//     address: faker.address.city(),
//     profission: faker.random.word(),
//     avatar: faker.image.avatar(),
//     role: 'VOLUNTEER',
//     hashedPassword: faker.random.alphaNumeric(),
//     createdAt: faker.date.past(),
//     updatedAt: faker.date.past(),
//     socialOrganizationIDs: [],
//     socialProjectIDs: [],
//     eventIDs: [],
//     socialProjects: [
//       {
//         id: '11',
//         name: faker.name.fullName(),
//         coverImage: faker.image.animals(),
//         hashedPassword: faker.random.alphaNumeric(),
//         county: 'Luanda',
//         address: faker.address.city(),
//         sponsorIDs: [],
//         createdAt: faker.date.past(),
//         updatedAt: faker.date.past(),
//         socialOrganizationId: '',
//         // socialOrganization: MOCKED_SINGLE_ORG,
//         // sponsors: MOCKED_SPONSORS,
//         volunteerIDs: ['string', 'string', 'string'],
//         province: 'Luanda',
//         description: `Lorem ipsum dolor sit amet consectetur adipiscing elit, ridiculus duis fringilla at cum ultricies, massa habitasse tellus ante inceptos morbi. Dignissim in tristique nisl integer, fusce laoreet accumsan, venenatis eget suspendisse. Suscipit est commodo venenatis iaculis tempus nibh dictum, auctor blandit praesent odio vel pharetra convallis placerat, ullamcorper nostra ligula morbi egestas erat. Velit magnis cras vehicula rhoncus quam nulla, nisl per turpis suspendisse luctus, eleifend egestas scelerisque nibh nullam. Magnis vulputate nulla fusce egestas volutpat dapibus vestibulum penatibus laoreet sollicitudin augue, nam non habitasse nisi habitant ligula per vitae pulvinar cursus. Purus lacinia interdum aenean tincidunt placerat fringilla pellentesque ligula habitant tempus, tristique volutpat turpis mattis faucibus in vulputate pretium nullam erat, dis condimentum tortor molestie ac lectus natoque rhoncus netus.
//           Fringilla inceptos ante penatibus purus leo cubilia venenatis, quam laoreet nascetur congue lacinia et tempor placerat, feugiat fermentum donec hac diam a. Ullamcorper mus proin maecenas mollis lectus pharetra arcu, enim ad urna egestas non hac habitasse tempus, aenean tincidunt molestie auctor natoque nunc. Iaculis nascetur porttitor dictum eros nisi bibendum purus, class a nostra augue nibh. Cubilia eleifend lacinia montes tempor duis faucibus auctor cursus vestibulum, felis lobortis rutrum sollicitudin varius netus dis risus eget, blandit laoreet nascetur urna sem ligula volutpat magnis. Quisque etiam proin mauris sollicitudin id nibh litora euismod integer sed sociis, nostra facilisis bibendum parturient molestie pellentesque eget malesuada primis. Nullam egestas libero tempus ridiculus cubilia porttitor natoque sodales dignissim porta, quisque congue vel quam auctor tortor integer fames cum et, nec curabitur suspendisse elementum sociosqu dui mattis scelerisque hac. Sapien faucibus aenean habitant dictum dictumst pretium vitae sollicitudin curabitur cursus vivamus, tempus rhoncus viverra ornare sed consequat sociis per feugiat. Aptent bibendum fames eleifend a laoreet scelerisque volutpat pretium enim quam, condimentum nascetur justo tempor molestie auctor luctus fusce malesuada, ullamcorper dui diam mi nulla risus erat vestibulum nibh.`,
//       },
//     ],
//     socialOrganizations: [
//       {
//         id: '6',
//         avatar: faker.image.avatar(),
//         name: faker.name.fullName(),
//         coverImage: faker.image.animals(),
//         hashedPassword: faker.random.alphaNumeric(),
//         responsibleName: faker.name.fullName(),
//         responsibleEmail: faker.internet.email(),
//         responsiblePhone: '9535435634',
//         telephone: faker.phone.number(),
//         email: faker.internet.email(),
//         description:
//           'Lorem ipsum dolor sit amet consectetur adipiscing elit cum gravida leo, duis phasellus in aliquam conubia tincidunt vitae sem accumsan ante, rhoncus lectus habitasse fusce condimentum mi ornare fermentum litora. Ridiculus cubilia nisi ultrices a convallis facilisis leo erat sociis, mi condimentum sapien arcu semper morbi nullam commodo molestie, netus vivamus risus sociosqu maecenas pulvinar nibh elementum. Laoreet pretium aliquam molestie imperdiet nullam fermentum, aenean nisi duis phasellus blandit, sagittis inceptos venenatis dis ultrices. Pellentesque nulla per parturient suspendisse posuere sagittis, mauris tortor porta feugiat vehicula, habitant laoreet torquent dictum semper. Urna sed tellus montes lectus ullamcorper eu etiam semper, commodo risus mi ad quam curabitur ornare, sagittis odio at rutrum turpis magnis feugiat. Sollicitudin nascetur praesent mus arcu massa eget nec fringilla etiam, porta magnis parturient vulputate nunc at mattis urna, fusce torquent fermentum dui ultrices odio aliquam facilisis. Ornare laoreet quis urna dui quam nulla molestie habitant, aenean eros malesuada vel curabitur purus rutrum ante fusce, convallis aliquet morbi suspendisse a praesent posuere. Quisque viverra consequat etiam mauris scelerisque nostra, sollicitudin phasellus curabitur magna auctor mattis semper, feugiat integer eget torquent eros. Aptent per ultrices vulputate tellus eros tempor tortor class vel, facilisis viverra quisque enim rhoncus ligula iaculis consequat aliquam, hac tincidunt libero nunc aliquet porttitor vivamus sodales. Nulla ante nullam tincidunt elementum viverra turpis, dignissim sapien egestas phasellus curabitur vulputate, primis ad praesent ut neque. Ultricies feugiat sem dis tristique class ligula vitae donec nulla curae nascetur, hendrerit dictum egestas vestibulum interdum neque nibh venenatis euismod. Fusce fringilla praesent tellus egestas neque ornare dis commodo mus fermentum massa, arcu at porta cras eu aliquet pharetra nec parturient. Magna ultricies hendrerit consequat senectus ut pellentesque vel tortor dapibus, sociis egestas mauris dui nam feugiat fusce facilisi, auctor convallis velit eget posuere eu orci tempus.',
//         province: 'Luanda',
//         county: 'Luanda',
//         address: faker.address.city(),
//         createdAt: faker.date.past(),
//         updatedAt: faker.date.past(),
//         volunteerIDs: [],
//         sponsorIDs: [],
//         // sponsors: MOCKED_SPONSORS,
//         // volunteers: MOCKED_VOLUNTEERS,
//         // events: MOCKED_EVENTS,
//         // socialProjects: MOCKED_SOCIAL_PROJECTS,
//       },
//     ],
//     events: [
//       {
//         id: '1',
//         title: 'Lorem ipsum dolor sit amet',
//         province: 'Luanda',
//         county: 'Luanda',
//         address: faker.address.city(),
//         startDate: new Date(),
//         endDate: new Date(),
//         status: EventStatus.UPCOMMING,
//         createdAt: faker.date.past(),
//         updatedAt: faker.date.past(),
//         volunteerIDs: [],
//         socialOrganizationID: '',
//         sponsorIDs: [],
//         // volunteers: MOCKED_VOLUNTEERS,
//         // sponsors: MOCKED_SPONSORS,
//         // socialOrganization: MOCKED_SINGLE_ORG,
//         // participants: MOCKED_VOLUNTEERS,
//       },
//     ],
//   },
// ];

function generateRandomString() {
  const chars = 'abcdef0123456789'; // Hexadecimal characters
  let result = '';

  for (let i = 0; i < 24; i++) {
    const randomIndex = Math.floor(Math.random() * chars.length);
    result += chars.charAt(randomIndex);
  }

  return result;
}

// Example usage to generate a string like MongoDB ObjectId
// const generatedString = generateRandomString(); // 24 characters long
// console.log(generatedString);

const email = faker.internet.email();

const createdUser = {
  // id: generateRandomString(),
  telephone: faker.phone.number(),
  address: faker.address.city(),
  profission: faker.random.word(),
  avatar: faker.image.avatar(),
  role: Role.VOLUNTEER,
  hashedPassword: faker.random.alphaNumeric(),
  createdAt: faker.date.past(),
  updatedAt: faker.date.past(),
  socialOrganizationIDs: [],
  socialProjectIDs: [],
  eventIDs: [],
  // socialProjects: [
  //   {
  //     id: '11',
  //     name: faker.name.fullName(),
  //     coverImage: faker.image.animals(),
  //     hashedPassword: faker.random.alphaNumeric(),
  //     county: 'Luanda',
  //     address: faker.address.city(),
  //     sponsorIDs: [],
  //     createdAt: faker.date.past(),
  //     updatedAt: faker.date.past(),
  //     socialOrganizationId: '',
  //     socialOrganization: {
  //       id: '5',
  //       avatar: faker.image.avatar(),
  //       name: faker.name.fullName(),
  //       coverImage: faker.image.animals(),
  //       hashedPassword: faker.random.alphaNumeric(),
  //       responsibleName: faker.name.fullName(),
  //       responsibleEmail: faker.internet.email(),
  //       responsiblePhone: '9535435634',
  //       telephone: faker.phone.number(),
  //       email: faker.internet.email(),
  //       description:
  //         'Lorem ipsum dolor sit amet consectetur adipiscing elit cum gravida leo, duis phasellus in aliquam conubia tincidunt vitae sem accumsan ante, rhoncus lectus habitasse fusce condimentum mi ornare fermentum litora. Ridiculus cubilia nisi ultrices a convallis facilisis leo erat sociis, mi condimentum sapien arcu semper morbi nullam commodo molestie, netus vivamus risus sociosqu maecenas pulvinar nibh elementum. Laoreet pretium aliquam molestie imperdiet nullam fermentum, aenean nisi duis phasellus blandit, sagittis inceptos venenatis dis ultrices. Pellentesque nulla per parturient suspendisse posuere sagittis, mauris tortor porta feugiat vehicula, habitant laoreet torquent dictum semper. Urna sed tellus montes lectus ullamcorper eu etiam semper, commodo risus mi ad quam curabitur ornare, sagittis odio at rutrum turpis magnis feugiat. Sollicitudin nascetur praesent mus arcu massa eget nec fringilla etiam, porta magnis parturient vulputate nunc at mattis urna, fusce torquent fermentum dui ultrices odio aliquam facilisis. Ornare laoreet quis urna dui quam nulla molestie habitant, aenean eros malesuada vel curabitur purus rutrum ante fusce, convallis aliquet morbi suspendisse a praesent posuere. Quisque viverra consequat etiam mauris scelerisque nostra, sollicitudin phasellus curabitur magna auctor mattis semper, feugiat integer eget torquent eros. Aptent per ultrices vulputate tellus eros tempor tortor class vel, facilisis viverra quisque enim rhoncus ligula iaculis consequat aliquam, hac tincidunt libero nunc aliquet porttitor vivamus sodales. Nulla ante nullam tincidunt elementum viverra turpis, dignissim sapien egestas phasellus curabitur vulputate, primis ad praesent ut neque. Ultricies feugiat sem dis tristique class ligula vitae donec nulla curae nascetur, hendrerit dictum egestas vestibulum interdum neque nibh venenatis euismod. Fusce fringilla praesent tellus egestas neque ornare dis commodo mus fermentum massa, arcu at porta cras eu aliquet pharetra nec parturient. Magna ultricies hendrerit consequat senectus ut pellentesque vel tortor dapibus, sociis egestas mauris dui nam feugiat fusce facilisi, auctor convallis velit eget posuere eu orci tempus.',
  //       province: 'Bengo',
  //       county: 'Bengo',
  //       address: faker.address.city(),
  //       createdAt: faker.date.past(),
  //       updatedAt: faker.date.past(),
  //       volunteerIDs: [],
  //       sponsorIDs: [],
  //       // sponsors: MOCKED_SPONSORS,
  //       volunteers: [],
  //       events: [],
  //       socialProjects: [],
  //     },
  //     volunteerIDs: ['string', 'string', 'string'],
  //     province: 'Luanda',
  //     description: `Lorem ipsum dolor sit amet consectetur adipiscing elit, ridiculus duis fringilla at cum ultricies, massa habitasse tellus ante inceptos morbi. Dignissim in tristique nisl integer, fusce laoreet accumsan, venenatis eget suspendisse. Suscipit est commodo venenatis iaculis tempus nibh dictum, auctor blandit praesent odio vel pharetra convallis placerat, ullamcorper nostra ligula morbi egestas erat. Velit magnis cras vehicula rhoncus quam nulla, nisl per turpis suspendisse luctus, eleifend egestas scelerisque nibh nullam. Magnis vulputate nulla fusce egestas volutpat dapibus vestibulum penatibus laoreet sollicitudin augue, nam non habitasse nisi habitant ligula per vitae pulvinar cursus. Purus lacinia interdum aenean tincidunt placerat fringilla pellentesque ligula habitant tempus, tristique volutpat turpis mattis faucibus in vulputate pretium nullam erat, dis condimentum tortor molestie ac lectus natoque rhoncus netus.
  //     Fringilla inceptos ante penatibus purus leo cubilia venenatis, quam laoreet nascetur congue lacinia et tempor placerat, feugiat fermentum donec hac diam a. Ullamcorper mus proin maecenas mollis lectus pharetra arcu, enim ad urna egestas non hac habitasse tempus, aenean tincidunt molestie auctor natoque nunc. Iaculis nascetur porttitor dictum eros nisi bibendum purus, class a nostra augue nibh. Cubilia eleifend lacinia montes tempor duis faucibus auctor cursus vestibulum, felis lobortis rutrum sollicitudin varius netus dis risus eget, blandit laoreet nascetur urna sem ligula volutpat magnis. Quisque etiam proin mauris sollicitudin id nibh litora euismod integer sed sociis, nostra facilisis bibendum parturient molestie pellentesque eget malesuada primis. Nullam egestas libero tempus ridiculus cubilia porttitor natoque sodales dignissim porta, quisque congue vel quam auctor tortor integer fames cum et, nec curabitur suspendisse elementum sociosqu dui mattis scelerisque hac. Sapien faucibus aenean habitant dictum dictumst pretium vitae sollicitudin curabitur cursus vivamus, tempus rhoncus viverra ornare sed consequat sociis per feugiat. Aptent bibendum fames eleifend a laoreet scelerisque volutpat pretium enim quam, condimentum nascetur justo tempor molestie auctor luctus fusce malesuada, ullamcorper dui diam mi nulla risus erat vestibulum nibh.`,
  //   },
  // ],
  // socialOrganizations: [
  //   {
  //     id: '6',
  //     avatar: faker.image.avatar(),
  //     name: faker.name.fullName(),
  //     coverImage: faker.image.animals(),
  //     hashedPassword: faker.random.alphaNumeric(),
  //     responsibleName: faker.name.fullName(),
  //     responsibleEmail: faker.internet.email(),
  //     responsiblePhone: '9535435634',
  //     telephone: faker.phone.number(),
  //     email: faker.internet.email(),
  //     description:
  //       'Lorem ipsum dolor sit amet consectetur adipiscing elit cum gravida leo, duis phasellus in aliquam conubia tincidunt vitae sem accumsan ante, rhoncus lectus habitasse fusce condimentum mi ornare fermentum litora. Ridiculus cubilia nisi ultrices a convallis facilisis leo erat sociis, mi condimentum sapien arcu semper morbi nullam commodo molestie, netus vivamus risus sociosqu maecenas pulvinar nibh elementum. Laoreet pretium aliquam molestie imperdiet nullam fermentum, aenean nisi duis phasellus blandit, sagittis inceptos venenatis dis ultrices. Pellentesque nulla per parturient suspendisse posuere sagittis, mauris tortor porta feugiat vehicula, habitant laoreet torquent dictum semper. Urna sed tellus montes lectus ullamcorper eu etiam semper, commodo risus mi ad quam curabitur ornare, sagittis odio at rutrum turpis magnis feugiat. Sollicitudin nascetur praesent mus arcu massa eget nec fringilla etiam, porta magnis parturient vulputate nunc at mattis urna, fusce torquent fermentum dui ultrices odio aliquam facilisis. Ornare laoreet quis urna dui quam nulla molestie habitant, aenean eros malesuada vel curabitur purus rutrum ante fusce, convallis aliquet morbi suspendisse a praesent posuere. Quisque viverra consequat etiam mauris scelerisque nostra, sollicitudin phasellus curabitur magna auctor mattis semper, feugiat integer eget torquent eros. Aptent per ultrices vulputate tellus eros tempor tortor class vel, facilisis viverra quisque enim rhoncus ligula iaculis consequat aliquam, hac tincidunt libero nunc aliquet porttitor vivamus sodales. Nulla ante nullam tincidunt elementum viverra turpis, dignissim sapien egestas phasellus curabitur vulputate, primis ad praesent ut neque. Ultricies feugiat sem dis tristique class ligula vitae donec nulla curae nascetur, hendrerit dictum egestas vestibulum interdum neque nibh venenatis euismod. Fusce fringilla praesent tellus egestas neque ornare dis commodo mus fermentum massa, arcu at porta cras eu aliquet pharetra nec parturient. Magna ultricies hendrerit consequat senectus ut pellentesque vel tortor dapibus, sociis egestas mauris dui nam feugiat fusce facilisi, auctor convallis velit eget posuere eu orci tempus.',
  //     province: 'Luanda',
  //     county: 'Luanda',
  //     address: faker.address.city(),
  //     createdAt: faker.date.past(),
  //     updatedAt: faker.date.past(),
  //     volunteerIDs: [],
  //     sponsorIDs: [],
  //     // sponsors: MOCKED_SPONSORS,
  //     // volunteers: MOCKED_VOLUNTEERS,
  //     // events: MOCKED_EVENTS,
  //     // socialProjects: MOCKED_SOCIAL_PROJECTS,
  //   },
  // ],
  // events: [
  //   {
  //     id: '1',
  //     title: 'Lorem ipsum dolor sit amet',
  //     province: 'Luanda',
  //     county: 'Luanda',
  //     address: faker.address.city(),
  //     startDate: new Date(),
  //     endDate: new Date(),
  //     status: EventStatus.UPCOMMING,
  //     createdAt: faker.date.past(),
  //     updatedAt: faker.date.past(),
  //     volunteerIDs: [],
  //     socialOrganizationID: '',
  //     sponsorIDs: [],
  //     // volunteers: MOCKED_VOLUNTEERS,
  //     // sponsors: MOCKED_SPONSORS,
  //     // socialOrganization: MOCKED_SINGLE_ORG,
  //     // participants: MOCKED_VOLUNTEERS,
  //   },
  // ],
  // accounts: [
  //   {
  //     email,
  //     type: AccountType.USER,
  //   },
  // ],
};

const FAKE_USER = () => ({
  id: generateRandomString(),
  email: faker.internet.email(),
  name: faker.name.fullName(),
  telephone: faker.phone.number(),
  address: faker.address.city(),
  profission: faker.random.word(),
  avatar: faker.image.avatar(),
  role: Role.VOLUNTEER,
  hashedPassword: faker.random.alphaNumeric(),
  createdAt: faker.date.past(),
  updatedAt: faker.date.past(),
  socialOrganizationIDs: [],
  socialProjectIDs: [],
  eventIDs: [],
  birthDate: faker.date.past(),
  county: faker.address.county(),
  genre: Genre.MASCULINO,
  province: faker.address.state(), 
});
// const FAKE_USER_ACCOUNT = () => ({
//   id: 'string',
//   email: 'f@gmail.com',
//   type: AccountType.USER,
//   userId: 'userId',
//   user: createdUser,
// });

async function main() {
  console.log('SEEDING...');
  const users = Array.from({ length: 50 }, FAKE_USER);
  await prisma.user.createMany({ data: users });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => await prisma.$disconnect());
