name: Portal do Voluntario Deploy

on: 
  push:
    branches: [ main ]
    
jobs: 
  build: 
    runs-on: ubunto-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout/setup-node@v1
        with: 
          node-version: 12
      - run: npm install 
      - run: npm run build
      - uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: aws s3 sync ./.next s3://portal-do-voluntario
