name: Portal do Voluntário Deployment Workflow

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependecies
        run: npm install
        run: npm run build

      # Deploy to Netlify
      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          # Auth token to use with netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          # Your Netlify site id
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          # Command to install dependencies
          install_command: npm install
          # Command to build static website
          build_command: npm run build
          # Directory where built files are stored
          build_directory: '.next'
      # Deploy to AWS
      - name: AWS deploy
        - use: aws-actions/configure-aws-credentials@v1
          with: 
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
          - run: aws s3 sync ./.next s3://portal-do-voluntario
